image: docker

stages:
  - deploy

pages:
  stage: deploy
  tags:
    - docker
  image: python:3.7
  script:
    - cd docs 
    - pip3 install -r requirements.txt -q
    - make html
    - mv build/html ../public
    - ls -R
  artifacts:
    paths:
      - public
  only:
    - main
